### PR TITLE
MRG: clean up and simplification

### PR DESCRIPTION
**Pull request by ndawe**
This is work in progress. Just opening the PR now to help coordinate with @jpivarski 

I've removed unnecessary bits and will try to merge wroot and rroot components. This will hopefully become the standalone built-in backend for root_numpy.

**edit:** will merge wroot and rroot in a separate PR

### CODE REVIEW

**Comment by jpivarski** [comment]
So "bush" is not needed? What was that? Do you want me to merge this pull request--- so much has changed, I don't have a good way to evaluate it, but I'll trust your opinion.

In fact, I'll add you as an owner to this forked repository, so that you can push these on your own.

**Comment by ndawe** [comment]
Yeah, bush was his own build system but it is not needed to simply compile the examples.

**Comment by ndawe** [comment]
Thanks for adding me! I'll ping later before merging. The diffs are too big after applying astyle for github to show them all but the code is much easier to read now.

**Comment by ndawe** [comment]
Actually, maybe merging this now is better and I can follow up with combining rroot and wroot in a separate smaller PR where we can see diffs...

**Comment by jpivarski** [comment]
When GitHub was struggling to display the differences, I decided that I wouldn't be able to review them, even if I saw them. It's probably trying to show the full text of every file in the directory you deleted.

**Comment by ndawe** [comment]
This is good to merge now

**Comment by jpivarski** [comment]
Do you want me to press "merge" or will you be handling it? It's nice to put changes through pull requests, but only necessary to have one-guy-PRs, another-guy-merges if those changes are reviewable or if I had some criteria for reviewing them. Right now, I'd let you do what you want--- you have a clearer idea of what has to happen to this than I do.

**Comment by ndawe** [comment]
Merged :)

**Pull request merged**
